name: C/C++ CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: make
      run: make -j8
    - name: run
      run: ./program.exe < samples/sample.inp > sample.out
    - name: comparar
      run: diff -b samples/sample.cor sample.out
    - name: run
      run: ./program.exe < samples/sample1.inp > sample.out
    - name: comparar
      run: diff -b samples/sample1.cor sample.out
